# Image Info
PROMPT_KEY = "prompt"
NEGATIVE_KEY = "negative_prompt"
SEED_KEY = "seed"
STEP_KEY = "steps"
CHECK_POINT_KEY = "sd_model_checkpoint"
#----------------------------------------------------------------------
# Analysiser Info
EPOCH_KEY = "epoch"
LEARNING_RATE_KEY = "learning_rate"
BATCH_SIZE_KEY = "batch_size"
MIN_TRAIN_LOSS_KEY = "min_train_loss"
MIN_TEST_LOSS_KEY = "min_test_loss"
TRAIN_DATA_NAME_LIST = "training_data_list"
# Process Result
AVG_CORRECT_RATE_KEY = "avg_correct_rate"
AVG_REDUNDANT_RATE_KEY = "avg_redundant_rate"
AVG_LACK_RATE_KEY = "avg_lack_rate"
PROMPT_NUMBER_TABLE_KEY = "prompt_number_data"
PROMPT_GROUP_TABLE_KEY = "prompt_group_data"